### ISSUE TITLE
Sample config file

### ISSUE THREAD

**Issue by philippebourcier** [ovh/fossil#1]
Hi,

Would it be possible to create a "docs" dir with a sample config file ?

I see there is a bunch of commented lines of code in cmd/root.go... is it something that needs to be activated to use fossil on OVH Metrics ?

Thanks,
P.

**Comment by StevenLeRoux** [comment]
Hi Philippe!

Fossil acts as a proxy for the unauthenticated & plain text Graphite protocol. While receiving metric data, it will pushes these data points locally to a Beamium source dir where data will be consolidated, batched, and pushed to the available sinks regarding the defined routing rules.

Btw, If you're interested in Graphite : 
 - we're working on a managed fossil, so that you don't even have to set up your own.
 - we have the query API in alpha

Are you interested in testing any or both ?

**Comment by philippebourcier** [comment]
Hey Steven :)

Oh, I thought it would be pushing the data to Metrics over HTTPS "all-in-one".
But now I get the bigger picture... fossil will do that only if it is coupled with beamium (thought it was more like an option)... and there I can find that sample config file I was looking for :)

While I don't need any aggregation, I am sending data over potentially unreliable connections (Mobile network)... data that is not stored locally. The points are sent every hour, but each point is "super important" (ie: loosing it is not an option). So, I could use this system, with very long TTL in beamium as a buffer+retry-er ? Right ?

I guess your managed fossil won't help in that scenario :)

My remaining question is : How does Warp10 handle points sent 24 hours (or more) in the past ?

**Comment by StevenLeRoux** [comment]
Give your usecase and the need to not loose points, Fossil with Beamium is the right solution (but do you really need graphite then ? you could produce directly your metrics into the source directory of Beamium). Beamium has a configurable TTL

On Metrics data points are timestamped (by default on public regions) on a microsecond basis. Pushing points in the past is not a problem since : 

- it's just like pushing any other points (past, current, future). There is no processing on the fly that could slow down the ingestion, thus no difference between a current timestamp and a past one.
 - retention is based on the ingestion timestamp, not the datapoint timestamp. It means that for a 2 year retention, you could push data points from 10 years ago and have 2 years to work with your dataset.

**Comment by Flo354** [comment]
Hi @StevenLeRoux I am really interested in your managed fossil! Can I test it?

**Comment by StevenLeRoux** [comment]
Hi @Flo354 , Cool ! Do you know when you will need it ? ASAP or days/weeks from now ? 

This feature is not ready yet for prime time, but we could work together to make it work if you don't want to manage it at all before the opening.

**Comment by Flo354** [comment]
I need it ASAP and ready to be nightly tester

Le jeu. 28 déc. 2017 à 2:38 PM, Steven Le Roux <notifications@github.com> a
écrit :
